"""Generate human-readable markdown reports from structured data."""
from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Union

Row = Sequence[Union[str, int, float, None]]


@dataclass
class ReportSection:
    """One section of a markdown report."""

    title: str
    body: str = ""
    level: int = 2  # ## heading level (2–4)
    subsections: list[ReportSection] = field(default_factory=list)


class ReportGenerator:
    """Build markdown documents from sections, tables, and key-value blocks."""

    def generate(
        self,
        title: str,
        sections: Sequence[ReportSection],
        *,
        subtitle: str | None = None,
        footer: str | None = None,
    ) -> str:
        lines = [f"# {title}", ""]
        if subtitle:
            lines.extend([subtitle, ""])
        for section in sections:
            lines.extend(self._render_section(section))
        if footer:
            lines.extend(["---", "", footer, ""])
        return "\n".join(lines).rstrip() + "\n"

    def section_from_dict(
        self,
        title: str,
        data: dict[str, Any],
        *,
        level: int = 2,
    ) -> ReportSection:
        """Render a flat dict as a bullet list section."""
        lines = []
        for key, value in data.items():
            if isinstance(value, (dict, list)):
                lines.append(f"- **{key}:**")
                lines.append(f"  ```json\n  {self._mini_json(value)}\n  ```")
            else:
                lines.append(f"- **{key}:** {value}")
        return ReportSection(title=title, body="\n".join(lines), level=level)

    def table(self, headers: Sequence[str], rows: Sequence[Row]) -> str:
        """Render a GitHub-flavored markdown table."""
        if not headers:
            return ""
        lines = [
            "| " + " | ".join(str(h) for h in headers) + " |",
            "| " + " | ".join("---" for _ in headers) + " |",
        ]
        for row in rows:
            cells = list(row) + [""] * (len(headers) - len(row))
            lines.append("| " + " | ".join(self._cell(c) for c in cells[: len(headers)]) + " |")
        return "\n".join(lines)

    def key_values(self, pairs: Sequence[tuple[str, Any]]) -> str:
        lines = [f"- **{k}:** {v}" for k, v in pairs]
        return "\n".join(lines)

    def timestamp_footer(self, generator: str = "repo-intelligence-platform") -> str:
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        return f"Generated by {generator} on {ts}."

    def _render_section(self, section: ReportSection) -> list[str]:
        hashes = "#" * min(max(section.level, 2), 4)
        lines = [f"{hashes} {section.title}", ""]
        if section.body:
            lines.append(section.body)
            lines.append("")
        for sub in section.subsections:
            lines.extend(self._render_section(sub))
        return lines

    @staticmethod
    def _cell(value: Any) -> str:
        if value is None:
            return ""
        text = str(value).replace("|", "\\|").replace("\n", " ")
        return text

    @staticmethod
    def _mini_json(value: Any) -> str:
        import json

        return json.dumps(value, indent=2)[:500]
